### ISSUE TITLE
Request - Public User Profiles

### ISSUE THREAD

**Issue by daltonsutton** [Bixie/pagekit-userprofile#6]
I love that I'm able to add custom fields to users, but I feel it's a little pointless unless there some sort of public user profiles system that can show it off. 

Like someone would go /profile/username and see a public profile of that user with all the custom goodies.

Just a thought. Keep up the killer work!

**Comment by ghost** [comment]
This! Please

**Comment by brysont** [comment]
Any plans to implement this (extremely common/needed) feature? Been 2 months and no response from the devs.

**Comment by malles** [comment]
I'm sorry for the late reply.
I think that is a good idea, and will think about how to implement that.

**Comment by brysont** [comment]
Looking around a bit, I notice that there is a front-end profile view, so that's certainly a start. First thought looking at that class was that it just needs some extra permissions and to take the username as an argument to the profile controller. idk but might not be too crazy to implement on top of what you've already got.

Could go even further and accept the username or a slugged version of the full name, or display name, and offer it in configs as an option. Should satisfy every user that way. But that might not be feasible without adding the full/display name to the default configs either.

**Comment by malles** [comment]
See https://github.com/Bixie/pagekit-userprofile/tree/profiles-view :)

I've set it up verybasic now. Will look at slugged routing for username/name

**Comment by malles** [comment]
It took a bit longer, but this is ready for release now. Please update Extension and Framework to try it out.

http://userprofile.bixie.org/members

**Comment by daltonsutton** [comment]
Guess who rocks? ^ This guy. 

Killer job. Will look at it more when I have some time. Super stoked.
